# Generated by Django 3.0.4 on 2020-03-06 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField()),
                ('time_created', models.TimeField()),
                ('data', models.TextField(blank=True)),
                ('done', models.BooleanField()),
                ('complete_by_date', models.DateField()),
                ('complete_by_time', models.TimeField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Login')),
            ],
        ),
    ]
